// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAEFvrR7cksVFBEhwcDTSW_HlImkE1gvcE',
    appId: '1:791764874763:web:9564beb57cc39e1bad390e',
    messagingSenderId: '791764874763',
    projectId: 'sgs-projeto',
    authDomain: 'sgs-projeto.firebaseapp.com',
    storageBucket: 'sgs-projeto.appspot.com',
    measurementId: 'G-VPJE5QYZ9W',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB30wr_sSUUe0DjqXW-OtMyPZPWwVmRl04',
    appId: '1:791764874763:android:f7942eb4878039dcad390e',
    messagingSenderId: '791764874763',
    projectId: 'sgs-projeto',
    storageBucket: 'sgs-projeto.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyApBxoFHVA0_Q7hH9vcJwJnXF1B-e9NZVU',
    appId: '1:791764874763:ios:9c90ff400ad3bfbaad390e',
    messagingSenderId: '791764874763',
    projectId: 'sgs-projeto',
    storageBucket: 'sgs-projeto.appspot.com',
    iosBundleId: 'com.example.sgsApp',
  );
}
